### PR TITLE
Add orientation and standalone support mainfest

### PR DESCRIPTION
**Pull request by mskian**
- Add orientation Support in Manifest
- Replace `minimal-ui` with `standalone` (PWA Looks like a Native APP)

### CODE REVIEW

**Comment by daviddarnes** [comment]
Thanks for proposing this @mskian! I'm interested to know why you're proposing this 🙂

**Comment by mskian** [comment]
> Thanks for proposing this @mskian! I'm interested to know why you're proposing this

- Add orientation Support in Manifest - When the user rotated the device our site rotate 
- `minimal-ui` Open PWA with URL look like open via Browser but `standalone` open like a Native APP Example 
photo_2019-10-04_14-46-57

**Comment by mskian** [comment]
Hello...

**Comment by mskian** [comment]
@daviddarnes any update

**Comment by daviddarnes** [comment]
I think this might be more of a developer preference than a fix 🙂

**Pull request closed without merging**
