### PR TITLE
Filter data-schema stub

### LINKED ISSUE #227: Data schema stub
### Issue Summary

Data schema stub is making its way to the build output. 

> This is a data schema stub for Gatsby.js and is not used. It must exist for builds to function

This may belong more in `gatsby-source-ghost` but I'm not familiar enough with either code base to make that judgement call.

### To Reproduce

1. `gatsby build` with a valid contentApiKey

You can also see it on https://gatsby.ghost.org/

image

### Technical details:

```
    "@tryghost/helpers": "1.1.27",
    "@tryghost/helpers-gatsby": "1.0.31",
    "cheerio": "1.0.0-rc.3",
    "core-js": "^3.6.5",
    "gatsby": "2.23.20",
    "gatsby-awesome-pagination": "0.3.6",
    "gatsby-image": "2.4.12",
    "gatsby-plugin-advanced-sitemap": "1.5.5",
    "gatsby-plugin-catch-links": "2.3.10",
    "gatsby-plugin-fathom": "^1.1.0",
    "gatsby-plugin-feed": "2.5.10",
    "gatsby-plugin-force-trailing-slashes": "1.0.4",
    "gatsby-plugin-manifest": "2.4.17",
    "gatsby-plugin-offline": "3.2.16",
    "gatsby-plugin-prefetch-google-fonts": "^1.4.3",
    "gatsby-plugin-react-helmet": "3.3.9",
    "gatsby-plugin-sharp": "2.6.17",
    "gatsby-source-filesystem": "2.3.18",
    "gatsby-source-ghost": "4.0.5",
    "gatsby-transformer-sharp": "2.5.10",
```

### PR DESCRIPTION
**Pull request by endymion1818**
Filter data-schema stub out of posts on the index page. Fixes #227

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Thanks for this fix.

I think https://github.com/TryGhost/gatsby-starter-ghost/blob/bd811f68b4de845f44e7f0412384f3bfb3287a67/gatsby-node.js#L9-L48 probably needs to be updated as well, so that pages are not generated for the stub content.

**Comment by endymion1818** [comment]
Funny thing, they don't seem to be ... 

yours: https://gatsby.ghost.org/data-schema/
mine: https://freebabylon5.com/data-schema/

**Comment by paulmelnikow** [comment]
Hmmm, that is funny. I wonder why that is…

**Comment by aileen** [comment]
🙏 Thank you!

**Pull request merged**
