### PR TITLE
Updating to Gatsby V4 stable

### PR DESCRIPTION
**Pull request by rmatambo8**
Hi! In case you didn’t know, Gatsby is planning its next major version for Q4 of this year! In preparation, the Gatsby team is reaching out to maintainers for our most popular Starters to help make the upgrade to Gatsby 4 as smooth as possible.

This PR updates your Gatsby Starter to the alpha version of this next release, as well as some related plugins. It’s just in draft form for now, since the 4.0.0 version of Gatsby isn’t quite ready for release yet. We’re mainly testing updating Gatsby and the other official plugins to ensure that the Starter builds without errors.

You may see some warnings from packages that list `gatsby: ^3.0.0` as a peer dependency.  Don’t worry, we’ll come back and fix those before we take this PR out of draft mode when it’s ready to be merged.

* Note: Gatsby 4 requires Node v14. This is a change from Gatsby 3, which worked with Node v12.13 or newer.

Once version 4.0.0 is ready, we'll come back to update the dependencies and convert this draft to a PR for review. Until then, no action is required on your end. If you have any questions / concerns, let us know in the comments. 

Thanks again for all your work as a Gatsby maintainer. We’re so grateful to have you as part of our community. 💜

For more information on what’s coming with Gatsby v4, check out the [GitHub Discussion](https://github.com/gatsbyjs/gatsby/discussions/32860](https://github.com/gatsbyjs/gatsby/discussions/32860).

Changes:
- upgraded package.json to include gatsby 4 alpha packages
- updated the webpack config in `gatsby-node.js` to include webpack 5 polyfill changes
- Changed react import syntax to use preferred syntax
- Added recommended script commands to package.json
- checked accessibility: no critical issues
- updated `gatsby-image` to `gatsby-plugin-image`

### CODE REVIEW

**Comment by rmatambo8** [comment]
I recently upgraded everything to beta and it seems to work correctly on my machine, we're getting closer to the finish line 🐎  🎉

**Comment by rmatambo8** [comment]
I'm not sure why I'm getting the mixed content error from netlify and I didn't change any of the routing logic in the application, is this something you're familiar with?

**Comment by rmatambo8** [comment]
Gatsby 4 is GA today! Just updated the related dependencies to the ^4.0.0 versions. If everything looks good, feel free to merge!

👍 

One thing to note is:
`gatsby-plugin-feed` now requires the title to be set directly in order to run. I added `{title: "To title"}` to the generated RSS feed that would get overwritten by your setup step.

**Comment by agent-reed** [comment]
Would love to see this merged!

**Comment by ecda909** [comment]
I would also love to see this merged as well.

**Comment by aileen** [comment]
Closing in favour of #510

**Pull request closed without merging**
